# Test

In [1]:
print("This is a test")

import numpy as np

print(np.random.randn(10, 4))

This is a test
[[ 1.60911229  0.91007897  0.83054191  1.7364702 ]
 [ 0.4550351  -0.71659979  0.66291019  0.50932937]
 [ 0.8309185  -0.15138694 -0.16905043  3.03291083]
 [-0.54074524 -1.01105494  1.74976403  0.20565466]
 [ 2.54366665 -1.25530974  0.52283956  0.79707004]
 [ 0.74657973  0.13215762 -1.49316014  2.43436674]
 [ 0.31376456  0.77828904 -1.85010024 -0.43712198]
 [ 0.3053205  -1.00114574 -0.68732717 -0.59777082]
 [-0.42477307  0.01307358 -1.89229104  1.56048432]
 [ 0.23672216  1.18146024  0.48906788  2.11650568]]
